// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: api/v1/labcontainers.proto

package labcontainersv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifecycleAction int32

const (
	LifecycleAction_LIFECYCLE_ACTION_UNSPECIFIED LifecycleAction = 0
	LifecycleAction_POWER_OFF                    LifecycleAction = 1
	LifecycleAction_START                        LifecycleAction = 2
	LifecycleAction_RESTART                      LifecycleAction = 3
	LifecycleAction_REPLACE                      LifecycleAction = 4
	// SIGKILL the VM wrapper and QEMU without guest shutdown or cache flush.
	LifecycleAction_CRASH LifecycleAction = 5
)

// Enum value maps for LifecycleAction.
var (
	LifecycleAction_name = map[int32]string{
		0: "LIFECYCLE_ACTION_UNSPECIFIED",
		1: "POWER_OFF",
		2: "START",
		3: "RESTART",
		4: "REPLACE",
		5: "CRASH",
	}
	LifecycleAction_value = map[string]int32{
		"LIFECYCLE_ACTION_UNSPECIFIED": 0,
		"POWER_OFF":                    1,
		"START":                        2,
		"RESTART":                      3,
		"REPLACE":                      4,
		"CRASH":                        5,
	}
)

func (x LifecycleAction) Enum() *LifecycleAction {
	p := new(LifecycleAction)
	*p = x
	return p
}

func (x LifecycleAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_labcontainers_proto_enumTypes[0].Descriptor()
}

func (LifecycleAction) Type() protoreflect.EnumType {
	return &file_api_v1_labcontainers_proto_enumTypes[0]
}

func (x LifecycleAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleAction.Descriptor instead.
func (LifecycleAction) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{0}
}

type TopologySource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Source:
	//
	//	*TopologySource_Path
	//	*TopologySource_Yaml
	Source isTopologySource_Source `protobuf_oneof:"source"`
}

func (x *TopologySource) Reset() {
	*x = TopologySource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopologySource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologySource) ProtoMessage() {}

func (x *TopologySource) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologySource.ProtoReflect.Descriptor instead.
func (*TopologySource) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{1}
}

func (m *TopologySource) GetSource() isTopologySource_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (x *TopologySource) GetPath() string {
	if x, ok := x.GetSource().(*TopologySource_Path); ok {
		return x.Path
	}
	return ""
}

func (x *TopologySource) GetYaml() []byte {
	if x, ok := x.GetSource().(*TopologySource_Yaml); ok {
		return x.Yaml
	}
	return nil
}

type isTopologySource_Source interface {
	isTopologySource_Source()
}

type TopologySource_Path struct {
	Path string `protobuf:"bytes,1,opt,name=path,proto3,oneof"`
}

type TopologySource_Yaml struct {
	Yaml []byte `protobuf:"bytes,2,opt,name=yaml,proto3,oneof"`
}

func (*TopologySource_Path) isTopologySource_Source() {}

func (*TopologySource_Yaml) isTopologySource_Source() {}

type NodeExtension struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Control   string         `protobuf:"bytes,1,opt,name=control,proto3" json:"control,omitempty"`
	Bootstrap *BootstrapData `protobuf:"bytes,2,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	Disks     []*Disk        `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty"`
}

func (x *NodeExtension) Reset() {
	*x = NodeExtension{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeExtension) ProtoMessage() {}

func (x *NodeExtension) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeExtension.ProtoReflect.Descriptor instead.
func (*NodeExtension) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{2}
}

func (x *NodeExtension) GetControl() string {
	if x != nil {
		return x.Control
	}
	return ""
}

func (x *NodeExtension) GetBootstrap() *BootstrapData {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

func (x *NodeExtension) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

type BootstrapData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Format string `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Value  []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BootstrapData) Reset() {
	*x = BootstrapData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BootstrapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapData) ProtoMessage() {}

func (x *BootstrapData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapData.ProtoReflect.Descriptor instead.
func (*BootstrapData) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{3}
}

func (x *BootstrapData) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *BootstrapData) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Disk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes  uint64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Filesystem string `protobuf:"bytes,3,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	MountPoint string `protobuf:"bytes,4,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
}

func (x *Disk) Reset() {
	*x = Disk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{4}
}

func (x *Disk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Disk) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Disk) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *Disk) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

type LabSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topology            *TopologySource           `protobuf:"bytes,1,opt,name=topology,proto3" json:"topology,omitempty"`
	Nodes               map[string]*NodeExtension `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AllowExternalAccess bool                      `protobuf:"varint,3,opt,name=allow_external_access,json=allowExternalAccess,proto3" json:"allow_external_access,omitempty"`
	ArtifactDirectory   string                    `protobuf:"bytes,4,opt,name=artifact_directory,json=artifactDirectory,proto3" json:"artifact_directory,omitempty"`
	// name requests a stable Containerlab name for harnesses that must reconnect
	// across processes. Empty uses a collision-resistant per-session name.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LabSpec) Reset() {
	*x = LabSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LabSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabSpec) ProtoMessage() {}

func (x *LabSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabSpec.ProtoReflect.Descriptor instead.
func (*LabSpec) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{5}
}

func (x *LabSpec) GetTopology() *TopologySource {
	if x != nil {
		return x.Topology
	}
	return nil
}

func (x *LabSpec) GetNodes() map[string]*NodeExtension {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *LabSpec) GetAllowExternalAccess() bool {
	if x != nil {
		return x.AllowExternalAccess
	}
	return false
}

func (x *LabSpec) GetArtifactDirectory() string {
	if x != nil {
		return x.ArtifactDirectory
	}
	return ""
}

func (x *LabSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec       *LabSpec          `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	TtlSeconds int64             `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Labels     map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSessionRequest) GetSpec() *LabSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CreateSessionRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *CreateSessionRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type SessionRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SessionRef) Reset() {
	*x = SessionRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRef) ProtoMessage() {}

func (x *SessionRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRef.ProtoReflect.Descriptor instead.
func (*SessionRef) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{7}
}

func (x *SessionRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State             string  `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	TopologyPath      string  `protobuf:"bytes,4,opt,name=topology_path,json=topologyPath,proto3" json:"topology_path,omitempty"`
	ArtifactDirectory string  `protobuf:"bytes,5,opt,name=artifact_directory,json=artifactDirectory,proto3" json:"artifact_directory,omitempty"`
	ExpiresUnix       int64   `protobuf:"varint,6,opt,name=expires_unix,json=expiresUnix,proto3" json:"expires_unix,omitempty"`
	ResumeToken       string  `protobuf:"bytes,7,opt,name=resume_token,json=resumeToken,proto3" json:"resume_token,omitempty"`
	Nodes             []*Node `protobuf:"bytes,8,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{8}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Session) GetTopologyPath() string {
	if x != nil {
		return x.TopologyPath
	}
	return ""
}

func (x *Session) GetArtifactDirectory() string {
	if x != nil {
		return x.ArtifactDirectory
	}
	return ""
}

func (x *Session) GetExpiresUnix() int64 {
	if x != nil {
		return x.ExpiresUnix
	}
	return 0
}

func (x *Session) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

func (x *Session) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type DestroySessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResumeToken string `protobuf:"bytes,2,opt,name=resume_token,json=resumeToken,proto3" json:"resume_token,omitempty"`
}

func (x *DestroySessionRequest) Reset() {
	*x = DestroySessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionRequest) ProtoMessage() {}

func (x *DestroySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionRequest.ProtoReflect.Descriptor instead.
func (*DestroySessionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{9}
}

func (x *DestroySessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DestroySessionRequest) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

type KeepSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TtlSeconds int64  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
}

func (x *KeepSessionRequest) Reset() {
	*x = KeepSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepSessionRequest) ProtoMessage() {}

func (x *KeepSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepSessionRequest.ProtoReflect.Descriptor instead.
func (*KeepSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{10}
}

func (x *KeepSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeepSessionRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type NodeRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Node      string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *NodeRef) Reset() {
	*x = NodeRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRef) ProtoMessage() {}

func (x *NodeRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRef.ProtoReflect.Descriptor instead.
func (*NodeRef) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{11}
}

func (x *NodeRef) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *NodeRef) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{12}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ExecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node          *NodeRef `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Argv          []string `protobuf:"bytes,2,rep,name=argv,proto3" json:"argv,omitempty"`
	Stdin         []byte   `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	TimeoutMillis int64    `protobuf:"varint,4,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{13}
}

func (x *ExecRequest) GetNode() *NodeRef {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ExecRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ExecRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

func (x *ExecRequest) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

type ExecResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stdout   []byte `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr   []byte `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode int32  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{14}
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type PutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node    *NodeRef `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Path    string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Mode    uint32   `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Content []byte   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{15}
}

func (x *PutRequest) GetNode() *NodeRef {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *PutRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PutRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *PutRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type LifecycleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node      *NodeRef        `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Action    LifecycleAction `protobuf:"varint,2,opt,name=action,proto3,enum=labcontainers.v1.LifecycleAction" json:"action,omitempty"`
	Bootstrap *BootstrapData  `protobuf:"bytes,3,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
}

func (x *LifecycleRequest) Reset() {
	*x = LifecycleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleRequest) ProtoMessage() {}

func (x *LifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleRequest.ProtoReflect.Descriptor instead.
func (*LifecycleRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{16}
}

func (x *LifecycleRequest) GetNode() *NodeRef {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *LifecycleRequest) GetAction() LifecycleAction {
	if x != nil {
		return x.Action
	}
	return LifecycleAction_LIFECYCLE_ACTION_UNSPECIFIED
}

func (x *LifecycleRequest) GetBootstrap() *BootstrapData {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

type Netem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DelayMillis       int64   `protobuf:"varint,1,opt,name=delay_millis,json=delayMillis,proto3" json:"delay_millis,omitempty"`
	JitterMillis      int64   `protobuf:"varint,2,opt,name=jitter_millis,json=jitterMillis,proto3" json:"jitter_millis,omitempty"`
	LossPercent       float64 `protobuf:"fixed64,3,opt,name=loss_percent,json=lossPercent,proto3" json:"loss_percent,omitempty"`
	RateKbit          uint64  `protobuf:"varint,4,opt,name=rate_kbit,json=rateKbit,proto3" json:"rate_kbit,omitempty"`
	CorruptionPercent float64 `protobuf:"fixed64,5,opt,name=corruption_percent,json=corruptionPercent,proto3" json:"corruption_percent,omitempty"`
}

func (x *Netem) Reset() {
	*x = Netem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Netem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Netem) ProtoMessage() {}

func (x *Netem) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Netem.ProtoReflect.Descriptor instead.
func (*Netem) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{17}
}

func (x *Netem) GetDelayMillis() int64 {
	if x != nil {
		return x.DelayMillis
	}
	return 0
}

func (x *Netem) GetJitterMillis() int64 {
	if x != nil {
		return x.JitterMillis
	}
	return 0
}

func (x *Netem) GetLossPercent() float64 {
	if x != nil {
		return x.LossPercent
	}
	return 0
}

func (x *Netem) GetRateKbit() uint64 {
	if x != nil {
		return x.RateKbit
	}
	return 0
}

func (x *Netem) GetCorruptionPercent() float64 {
	if x != nil {
		return x.CorruptionPercent
	}
	return 0
}

type Partition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left     []string `protobuf:"bytes,1,rep,name=left,proto3" json:"left,omitempty"`
	Right    []string `protobuf:"bytes,2,rep,name=right,proto3" json:"right,omitempty"`
	Directed bool     `protobuf:"varint,3,opt,name=directed,proto3" json:"directed,omitempty"`
}

func (x *Partition) Reset() {
	*x = Partition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partition) ProtoMessage() {}

func (x *Partition) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partition.ProtoReflect.Descriptor instead.
func (*Partition) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{18}
}

func (x *Partition) GetLeft() []string {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *Partition) GetRight() []string {
	if x != nil {
		return x.Right
	}
	return nil
}

func (x *Partition) GetDirected() bool {
	if x != nil {
		return x.Directed
	}
	return false
}

type LinkState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node      string `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Interface string `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	Up        bool   `protobuf:"varint,3,opt,name=up,proto3" json:"up,omitempty"`
}

func (x *LinkState) Reset() {
	*x = LinkState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkState) ProtoMessage() {}

func (x *LinkState) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkState.ProtoReflect.Descriptor instead.
func (*LinkState) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{19}
}

func (x *LinkState) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *LinkState) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *LinkState) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

type ApplyFaultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are assignable to Fault:
	//
	//	*ApplyFaultRequest_Netem
	//	*ApplyFaultRequest_Partition
	//	*ApplyFaultRequest_LinkState
	Fault     isApplyFaultRequest_Fault `protobuf_oneof:"fault"`
	Node      string                    `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	Interface string                    `protobuf:"bytes,6,opt,name=interface,proto3" json:"interface,omitempty"`
}

func (x *ApplyFaultRequest) Reset() {
	*x = ApplyFaultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyFaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFaultRequest) ProtoMessage() {}

func (x *ApplyFaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFaultRequest.ProtoReflect.Descriptor instead.
func (*ApplyFaultRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{20}
}

func (x *ApplyFaultRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (m *ApplyFaultRequest) GetFault() isApplyFaultRequest_Fault {
	if m != nil {
		return m.Fault
	}
	return nil
}

func (x *ApplyFaultRequest) GetNetem() *Netem {
	if x, ok := x.GetFault().(*ApplyFaultRequest_Netem); ok {
		return x.Netem
	}
	return nil
}

func (x *ApplyFaultRequest) GetPartition() *Partition {
	if x, ok := x.GetFault().(*ApplyFaultRequest_Partition); ok {
		return x.Partition
	}
	return nil
}

func (x *ApplyFaultRequest) GetLinkState() *LinkState {
	if x, ok := x.GetFault().(*ApplyFaultRequest_LinkState); ok {
		return x.LinkState
	}
	return nil
}

func (x *ApplyFaultRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ApplyFaultRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

type isApplyFaultRequest_Fault interface {
	isApplyFaultRequest_Fault()
}

type ApplyFaultRequest_Netem struct {
	Netem *Netem `protobuf:"bytes,2,opt,name=netem,proto3,oneof"`
}

type ApplyFaultRequest_Partition struct {
	Partition *Partition `protobuf:"bytes,3,opt,name=partition,proto3,oneof"`
}

type ApplyFaultRequest_LinkState struct {
	LinkState *LinkState `protobuf:"bytes,4,opt,name=link_state,json=linkState,proto3,oneof"`
}

func (*ApplyFaultRequest_Netem) isApplyFaultRequest_Fault() {}

func (*ApplyFaultRequest_Partition) isApplyFaultRequest_Fault() {}

func (*ApplyFaultRequest_LinkState) isApplyFaultRequest_Fault() {}

type FaultRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FaultRef) Reset() {
	*x = FaultRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaultRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaultRef) ProtoMessage() {}

func (x *FaultRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaultRef.ProtoReflect.Descriptor instead.
func (*FaultRef) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{21}
}

func (x *FaultRef) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FaultRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Fault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind   string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Active bool   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *Fault) Reset() {
	*x = Fault{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fault) ProtoMessage() {}

func (x *Fault) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fault.ProtoReflect.Descriptor instead.
func (*Fault) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{22}
}

func (x *Fault) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Fault) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Fault) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type TimelineAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AtMillis int64 `protobuf:"varint,1,opt,name=at_millis,json=atMillis,proto3" json:"at_millis,omitempty"`
	// Types that are assignable to Action:
	//
	//	*TimelineAction_Lifecycle
	//	*TimelineAction_ApplyFault
	//	*TimelineAction_RevertFault
	//	*TimelineAction_Exec
	//	*TimelineAction_WaitExec
	Action isTimelineAction_Action `protobuf_oneof:"action"`
}

func (x *TimelineAction) Reset() {
	*x = TimelineAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimelineAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineAction) ProtoMessage() {}

func (x *TimelineAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineAction.ProtoReflect.Descriptor instead.
func (*TimelineAction) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{23}
}

func (x *TimelineAction) GetAtMillis() int64 {
	if x != nil {
		return x.AtMillis
	}
	return 0
}

func (m *TimelineAction) GetAction() isTimelineAction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *TimelineAction) GetLifecycle() *LifecycleRequest {
	if x, ok := x.GetAction().(*TimelineAction_Lifecycle); ok {
		return x.Lifecycle
	}
	return nil
}

func (x *TimelineAction) GetApplyFault() *ApplyFaultRequest {
	if x, ok := x.GetAction().(*TimelineAction_ApplyFault); ok {
		return x.ApplyFault
	}
	return nil
}

func (x *TimelineAction) GetRevertFault() *FaultRef {
	if x, ok := x.GetAction().(*TimelineAction_RevertFault); ok {
		return x.RevertFault
	}
	return nil
}

func (x *TimelineAction) GetExec() *ExecRequest {
	if x, ok := x.GetAction().(*TimelineAction_Exec); ok {
		return x.Exec
	}
	return nil
}

func (x *TimelineAction) GetWaitExec() *WaitExec {
	if x, ok := x.GetAction().(*TimelineAction_WaitExec); ok {
		return x.WaitExec
	}
	return nil
}

type isTimelineAction_Action interface {
	isTimelineAction_Action()
}

type TimelineAction_Lifecycle struct {
	Lifecycle *LifecycleRequest `protobuf:"bytes,2,opt,name=lifecycle,proto3,oneof"`
}

type TimelineAction_ApplyFault struct {
	ApplyFault *ApplyFaultRequest `protobuf:"bytes,3,opt,name=apply_fault,json=applyFault,proto3,oneof"`
}

type TimelineAction_RevertFault struct {
	RevertFault *FaultRef `protobuf:"bytes,4,opt,name=revert_fault,json=revertFault,proto3,oneof"`
}

type TimelineAction_Exec struct {
	Exec *ExecRequest `protobuf:"bytes,5,opt,name=exec,proto3,oneof"`
}

type TimelineAction_WaitExec struct {
	WaitExec *WaitExec `protobuf:"bytes,6,opt,name=wait_exec,json=waitExec,proto3,oneof"`
}

func (*TimelineAction_Lifecycle) isTimelineAction_Action() {}

func (*TimelineAction_ApplyFault) isTimelineAction_Action() {}

func (*TimelineAction_RevertFault) isTimelineAction_Action() {}

func (*TimelineAction_Exec) isTimelineAction_Action() {}

func (*TimelineAction_WaitExec) isTimelineAction_Action() {}

// WaitExec retries a guest predicate until its result matches, then allows the
// next timeline action to run. This makes event -> fault sequencing explicit
// instead of relying on sleeps that can miss short-lived states.
type WaitExec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exec             *ExecRequest `protobuf:"bytes,1,opt,name=exec,proto3" json:"exec,omitempty"`
	RetryMillis      int64        `protobuf:"varint,2,opt,name=retry_millis,json=retryMillis,proto3" json:"retry_millis,omitempty"`
	TimeoutMillis    int64        `protobuf:"varint,3,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	ExpectedExitCode int32        `protobuf:"varint,4,opt,name=expected_exit_code,json=expectedExitCode,proto3" json:"expected_exit_code,omitempty"`
	StdoutContains   []byte       `protobuf:"bytes,5,opt,name=stdout_contains,json=stdoutContains,proto3" json:"stdout_contains,omitempty"`
	StderrContains   []byte       `protobuf:"bytes,6,opt,name=stderr_contains,json=stderrContains,proto3" json:"stderr_contains,omitempty"`
}

func (x *WaitExec) Reset() {
	*x = WaitExec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitExec) ProtoMessage() {}

func (x *WaitExec) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitExec.ProtoReflect.Descriptor instead.
func (*WaitExec) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{24}
}

func (x *WaitExec) GetExec() *ExecRequest {
	if x != nil {
		return x.Exec
	}
	return nil
}

func (x *WaitExec) GetRetryMillis() int64 {
	if x != nil {
		return x.RetryMillis
	}
	return 0
}

func (x *WaitExec) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

func (x *WaitExec) GetExpectedExitCode() int32 {
	if x != nil {
		return x.ExpectedExitCode
	}
	return 0
}

func (x *WaitExec) GetStdoutContains() []byte {
	if x != nil {
		return x.StdoutContains
	}
	return nil
}

func (x *WaitExec) GetStderrContains() []byte {
	if x != nil {
		return x.StderrContains
	}
	return nil
}

type RunTimelineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string            `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Actions   []*TimelineAction `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (x *RunTimelineRequest) Reset() {
	*x = RunTimelineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTimelineRequest) ProtoMessage() {}

func (x *RunTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTimelineRequest.ProtoReflect.Descriptor instead.
func (*RunTimelineRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{25}
}

func (x *RunTimelineRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunTimelineRequest) GetActions() []*TimelineAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type TimelineResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Completed int32    `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	FaultIds  []string `protobuf:"bytes,2,rep,name=fault_ids,json=faultIds,proto3" json:"fault_ids,omitempty"`
}

func (x *TimelineResult) Reset() {
	*x = TimelineResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_labcontainers_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimelineResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineResult) ProtoMessage() {}

func (x *TimelineResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_labcontainers_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineResult.ProtoReflect.Descriptor instead.
func (*TimelineResult) Descriptor() ([]byte, []int) {
	return file_api_v1_labcontainers_proto_rawDescGZIP(), []int{26}
}

func (x *TimelineResult) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *TimelineResult) GetFaultIds() []string {
	if x != nil {
		return x.FaultIds
	}
	return nil
}

var File_api_v1_labcontainers_proto protoreflect.FileDescriptor

var file_api_v1_labcontainers_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6c, 0x61,
	0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x46, 0x0a, 0x0e, 0x54, 0x6f, 0x70, 0x6f, 0x6c,
	0x6f, 0x67, 0x79, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x14, 0x0a, 0x04, 0x79, 0x61, 0x6d, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x04, 0x79, 0x61, 0x6d, 0x6c, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22,
	0x96, 0x01, 0x0a, 0x0d, 0x4e, 0x6f, 0x64, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x3d, 0x0a, 0x09, 0x62,
	0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x09, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x12, 0x2c, 0x0a, 0x05, 0x64, 0x69,
	0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x61, 0x62, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73,
	0x6b, 0x52, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x22, 0x3d, 0x0a, 0x0d, 0x42, 0x6f, 0x6f, 0x74,
	0x73, 0x74, 0x72, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x7a, 0x0a, 0x04, 0x44, 0x69, 0x73, 0x6b, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x22, 0xd5, 0x02, 0x0a, 0x07, 0x4c, 0x61, 0x62, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x3c, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x08, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x12, 0x3a, 0x0a,
	0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c,
	0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x61, 0x62, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x15, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2d, 0x0a,
	0x12, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x72, 0x74, 0x69, 0x66,
	0x61, 0x63, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x1a, 0x59, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x35, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xed, 0x01, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x61, 0x62, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73,
	0x70, 0x65, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x74, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x74, 0x6c, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x12, 0x4a, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x1a, 0x39, 0x0a, 0x0b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x1c, 0x0a, 0x0a, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8b, 0x02, 0x0a, 0x07, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74,
	0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x11, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x75,
	0x6e, 0x69, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x55, 0x6e, 0x69, 0x78, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2c, 0x0a, 0x05, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x4a, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x45, 0x0a, 0x12, 0x4b, 0x65, 0x65, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x74, 0x6c,
	0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x74, 0x74, 0x6c, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x3c, 0x0a, 0x07, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x66, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x30, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x45,
	0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x66, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67,
	0x76, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x76, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x74,
	0x64, 0x69, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6d,
	0x69, 0x6c, 0x6c, 0x69, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x22, 0x5b, 0x0a, 0x0c, 0x45, 0x78,
	0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x64, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f,
	0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78,
	0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65,
	0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x7d, 0x0a, 0x0a, 0x50, 0x75, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x66, 0x52, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xbb, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x66, 0x65, 0x63,
	0x79, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x61, 0x62, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x66, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6c, 0x61, 0x62,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72,
	0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x6f, 0x74,
	0x73, 0x74, 0x72, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x74, 0x73,
	0x74, 0x72, 0x61, 0x70, 0x22, 0xbe, 0x01, 0x0a, 0x05, 0x4e, 0x65, 0x74, 0x65, 0x6d, 0x12, 0x21,
	0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x69, 0x6c, 0x6c, 0x69,
	0x73, 0x12, 0x23, 0x0a, 0x0d, 0x6a, 0x69, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x6d, 0x69, 0x6c, 0x6c,
	0x69, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6a, 0x69, 0x74, 0x74, 0x65, 0x72,
	0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x6f, 0x73, 0x73, 0x5f, 0x70,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6c, 0x6f,
	0x73, 0x73, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x61, 0x74,
	0x65, 0x5f, 0x6b, 0x62, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x61,
	0x74, 0x65, 0x4b, 0x62, 0x69, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x6f, 0x72, 0x72, 0x75, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x11, 0x63, 0x6f, 0x72, 0x72, 0x75, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x74, 0x22, 0x51, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x4d, 0x0a, 0x09, 0x4c, 0x69, 0x6e, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x75, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x75, 0x70, 0x22, 0x99, 0x02, 0x0a, 0x11, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x46, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x05,
	0x6e, 0x65, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x61,
	0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e,
	0x65, 0x74, 0x65, 0x6d, 0x48, 0x00, 0x52, 0x05, 0x6e, 0x65, 0x74, 0x65, 0x6d, 0x12, 0x3b, 0x0a,
	0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x0a, 0x6c, 0x69,
	0x6e, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6c,
	0x69, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x22, 0x39, 0x0a, 0x08, 0x46, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x66, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43,
	0x0a, 0x05, 0x46, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x22, 0xf4, 0x02, 0x0a, 0x0e, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x74, 0x5f, 0x6d, 0x69, 0x6c,
	0x6c, 0x69, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x74, 0x4d, 0x69, 0x6c,
	0x6c, 0x69, 0x73, 0x12, 0x42, 0x0a, 0x09, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79,
	0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x69,
	0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x79,
	0x5f, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6c,
	0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x46, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x46, 0x61, 0x75, 0x6c, 0x74, 0x12,
	0x3f, 0x0a, 0x0c, 0x72, 0x65, 0x76, 0x65, 0x72, 0x74, 0x5f, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65,
	0x66, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x76, 0x65, 0x72, 0x74, 0x46, 0x61, 0x75, 0x6c, 0x74,
	0x12, 0x33, 0x0a, 0x04, 0x65, 0x78, 0x65, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x04, 0x65, 0x78, 0x65, 0x63, 0x12, 0x39, 0x0a, 0x09, 0x77, 0x61, 0x69, 0x74, 0x5f, 0x65, 0x78,
	0x65, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x69, 0x74,
	0x45, 0x78, 0x65, 0x63, 0x48, 0x00, 0x52, 0x08, 0x77, 0x61, 0x69, 0x74, 0x45, 0x78, 0x65, 0x63,
	0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x87, 0x02, 0x0a, 0x08, 0x57,
	0x61, 0x69, 0x74, 0x45, 0x78, 0x65, 0x63, 0x12, 0x31, 0x0a, 0x04, 0x65, 0x78, 0x65, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x65, 0x78, 0x65, 0x63, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65,
	0x74, 0x72, 0x79, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x72, 0x65, 0x74, 0x72, 0x79, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x12, 0x25, 0x0a,
	0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x69,
	0x6c, 0x6c, 0x69, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x5f, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x10, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x45, 0x78, 0x69, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x73, 0x74, 0x64,
	0x6f, 0x75, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x73,
	0x74, 0x64, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x73, 0x22, 0x6f, 0x0a, 0x12, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x07, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x61, 0x62,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4b, 0x0a, 0x0e, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x49,
	0x64, 0x73, 0x2a, 0x72, 0x0a, 0x0f, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x1c, 0x4c, 0x49, 0x46, 0x45, 0x43, 0x59, 0x43,
	0x4c, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x4f, 0x57, 0x45, 0x52,
	0x5f, 0x4f, 0x46, 0x46, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x03, 0x12, 0x0b,
	0x0a, 0x07, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x43,
	0x52, 0x41, 0x53, 0x48, 0x10, 0x05, 0x32, 0x83, 0x06, 0x0a, 0x0d, 0x4c, 0x61, 0x62, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x52, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x2e, 0x6c, 0x61, 0x62, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x6c, 0x61, 0x62,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x66, 0x1a, 0x19, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x52, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4e, 0x0a, 0x0b, 0x4b, 0x65, 0x65, 0x70, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6c,
	0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x04, 0x45, 0x78, 0x65, 0x63, 0x12,
	0x1d, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x1c, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x47, 0x0a, 0x09,
	0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x22, 0x2e, 0x6c, 0x61, 0x62, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x66,
	0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x4a, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x46, 0x61,
	0x75, 0x6c, 0x74, 0x12, 0x23, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x46, 0x61, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x75, 0x6c,
	0x74, 0x12, 0x42, 0x0a, 0x0b, 0x52, 0x65, 0x76, 0x65, 0x72, 0x74, 0x46, 0x61, 0x75, 0x6c, 0x74,
	0x12, 0x1a, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x66, 0x1a, 0x17, 0x2e, 0x6c,
	0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x55, 0x0a, 0x0b, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x24, 0x2e, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6c, 0x61, 0x62,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x39, 0x5a, 0x37,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x70, 0x6d, 0x61,
	0x6e, 0x61, 0x2f, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_labcontainers_proto_rawDescOnce sync.Once
	file_api_v1_labcontainers_proto_rawDescData = file_api_v1_labcontainers_proto_rawDesc
)

func file_api_v1_labcontainers_proto_rawDescGZIP() []byte {
	file_api_v1_labcontainers_proto_rawDescOnce.Do(func() {
		file_api_v1_labcontainers_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_labcontainers_proto_rawDescData)
	})
	return file_api_v1_labcontainers_proto_rawDescData
}

var file_api_v1_labcontainers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_labcontainers_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_api_v1_labcontainers_proto_goTypes = []interface{}{
	(LifecycleAction)(0),          // 0: labcontainers.v1.LifecycleAction
	(*Empty)(nil),                 // 1: labcontainers.v1.Empty
	(*TopologySource)(nil),        // 2: labcontainers.v1.TopologySource
	(*NodeExtension)(nil),         // 3: labcontainers.v1.NodeExtension
	(*BootstrapData)(nil),         // 4: labcontainers.v1.BootstrapData
	(*Disk)(nil),                  // 5: labcontainers.v1.Disk
	(*LabSpec)(nil),               // 6: labcontainers.v1.LabSpec
	(*CreateSessionRequest)(nil),  // 7: labcontainers.v1.CreateSessionRequest
	(*SessionRef)(nil),            // 8: labcontainers.v1.SessionRef
	(*Session)(nil),               // 9: labcontainers.v1.Session
	(*DestroySessionRequest)(nil), // 10: labcontainers.v1.DestroySessionRequest
	(*KeepSessionRequest)(nil),    // 11: labcontainers.v1.KeepSessionRequest
	(*NodeRef)(nil),               // 12: labcontainers.v1.NodeRef
	(*Node)(nil),                  // 13: labcontainers.v1.Node
	(*ExecRequest)(nil),           // 14: labcontainers.v1.ExecRequest
	(*ExecResponse)(nil),          // 15: labcontainers.v1.ExecResponse
	(*PutRequest)(nil),            // 16: labcontainers.v1.PutRequest
	(*LifecycleRequest)(nil),      // 17: labcontainers.v1.LifecycleRequest
	(*Netem)(nil),                 // 18: labcontainers.v1.Netem
	(*Partition)(nil),             // 19: labcontainers.v1.Partition
	(*LinkState)(nil),             // 20: labcontainers.v1.LinkState
	(*ApplyFaultRequest)(nil),     // 21: labcontainers.v1.ApplyFaultRequest
	(*FaultRef)(nil),              // 22: labcontainers.v1.FaultRef
	(*Fault)(nil),                 // 23: labcontainers.v1.Fault
	(*TimelineAction)(nil),        // 24: labcontainers.v1.TimelineAction
	(*WaitExec)(nil),              // 25: labcontainers.v1.WaitExec
	(*RunTimelineRequest)(nil),    // 26: labcontainers.v1.RunTimelineRequest
	(*TimelineResult)(nil),        // 27: labcontainers.v1.TimelineResult
	nil,                           // 28: labcontainers.v1.LabSpec.NodesEntry
	nil,                           // 29: labcontainers.v1.CreateSessionRequest.LabelsEntry
}
var file_api_v1_labcontainers_proto_depIdxs = []int32{
	4,  // 0: labcontainers.v1.NodeExtension.bootstrap:type_name -> labcontainers.v1.BootstrapData
	5,  // 1: labcontainers.v1.NodeExtension.disks:type_name -> labcontainers.v1.Disk
	2,  // 2: labcontainers.v1.LabSpec.topology:type_name -> labcontainers.v1.TopologySource
	28, // 3: labcontainers.v1.LabSpec.nodes:type_name -> labcontainers.v1.LabSpec.NodesEntry
	6,  // 4: labcontainers.v1.CreateSessionRequest.spec:type_name -> labcontainers.v1.LabSpec
	29, // 5: labcontainers.v1.CreateSessionRequest.labels:type_name -> labcontainers.v1.CreateSessionRequest.LabelsEntry
	13, // 6: labcontainers.v1.Session.nodes:type_name -> labcontainers.v1.Node
	12, // 7: labcontainers.v1.ExecRequest.node:type_name -> labcontainers.v1.NodeRef
	12, // 8: labcontainers.v1.PutRequest.node:type_name -> labcontainers.v1.NodeRef
	12, // 9: labcontainers.v1.LifecycleRequest.node:type_name -> labcontainers.v1.NodeRef
	0,  // 10: labcontainers.v1.LifecycleRequest.action:type_name -> labcontainers.v1.LifecycleAction
	4,  // 11: labcontainers.v1.LifecycleRequest.bootstrap:type_name -> labcontainers.v1.BootstrapData
	18, // 12: labcontainers.v1.ApplyFaultRequest.netem:type_name -> labcontainers.v1.Netem
	19, // 13: labcontainers.v1.ApplyFaultRequest.partition:type_name -> labcontainers.v1.Partition
	20, // 14: labcontainers.v1.ApplyFaultRequest.link_state:type_name -> labcontainers.v1.LinkState
	17, // 15: labcontainers.v1.TimelineAction.lifecycle:type_name -> labcontainers.v1.LifecycleRequest
	21, // 16: labcontainers.v1.TimelineAction.apply_fault:type_name -> labcontainers.v1.ApplyFaultRequest
	22, // 17: labcontainers.v1.TimelineAction.revert_fault:type_name -> labcontainers.v1.FaultRef
	14, // 18: labcontainers.v1.TimelineAction.exec:type_name -> labcontainers.v1.ExecRequest
	25, // 19: labcontainers.v1.TimelineAction.wait_exec:type_name -> labcontainers.v1.WaitExec
	14, // 20: labcontainers.v1.WaitExec.exec:type_name -> labcontainers.v1.ExecRequest
	24, // 21: labcontainers.v1.RunTimelineRequest.actions:type_name -> labcontainers.v1.TimelineAction
	3,  // 22: labcontainers.v1.LabSpec.NodesEntry.value:type_name -> labcontainers.v1.NodeExtension
	7,  // 23: labcontainers.v1.Labcontainers.CreateSession:input_type -> labcontainers.v1.CreateSessionRequest
	8,  // 24: labcontainers.v1.Labcontainers.GetSession:input_type -> labcontainers.v1.SessionRef
	10, // 25: labcontainers.v1.Labcontainers.DestroySession:input_type -> labcontainers.v1.DestroySessionRequest
	11, // 26: labcontainers.v1.Labcontainers.KeepSession:input_type -> labcontainers.v1.KeepSessionRequest
	14, // 27: labcontainers.v1.Labcontainers.Exec:input_type -> labcontainers.v1.ExecRequest
	16, // 28: labcontainers.v1.Labcontainers.Put:input_type -> labcontainers.v1.PutRequest
	17, // 29: labcontainers.v1.Labcontainers.Lifecycle:input_type -> labcontainers.v1.LifecycleRequest
	21, // 30: labcontainers.v1.Labcontainers.ApplyFault:input_type -> labcontainers.v1.ApplyFaultRequest
	22, // 31: labcontainers.v1.Labcontainers.RevertFault:input_type -> labcontainers.v1.FaultRef
	26, // 32: labcontainers.v1.Labcontainers.RunTimeline:input_type -> labcontainers.v1.RunTimelineRequest
	9,  // 33: labcontainers.v1.Labcontainers.CreateSession:output_type -> labcontainers.v1.Session
	9,  // 34: labcontainers.v1.Labcontainers.GetSession:output_type -> labcontainers.v1.Session
	1,  // 35: labcontainers.v1.Labcontainers.DestroySession:output_type -> labcontainers.v1.Empty
	9,  // 36: labcontainers.v1.Labcontainers.KeepSession:output_type -> labcontainers.v1.Session
	15, // 37: labcontainers.v1.Labcontainers.Exec:output_type -> labcontainers.v1.ExecResponse
	1,  // 38: labcontainers.v1.Labcontainers.Put:output_type -> labcontainers.v1.Empty
	13, // 39: labcontainers.v1.Labcontainers.Lifecycle:output_type -> labcontainers.v1.Node
	23, // 40: labcontainers.v1.Labcontainers.ApplyFault:output_type -> labcontainers.v1.Fault
	1,  // 41: labcontainers.v1.Labcontainers.RevertFault:output_type -> labcontainers.v1.Empty
	27, // 42: labcontainers.v1.Labcontainers.RunTimeline:output_type -> labcontainers.v1.TimelineResult
	33, // [33:43] is the sub-list for method output_type
	23, // [23:33] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_api_v1_labcontainers_proto_init() }
func file_api_v1_labcontainers_proto_init() {
	if File_api_v1_labcontainers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_labcontainers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopologySource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeExtension); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BootstrapData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Disk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LabSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroySessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Netem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Partition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyFaultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FaultRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fault); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimelineAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitExec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunTimelineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_labcontainers_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimelineResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1_labcontainers_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*TopologySource_Path)(nil),
		(*TopologySource_Yaml)(nil),
	}
	file_api_v1_labcontainers_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*ApplyFaultRequest_Netem)(nil),
		(*ApplyFaultRequest_Partition)(nil),
		(*ApplyFaultRequest_LinkState)(nil),
	}
	file_api_v1_labcontainers_proto_msgTypes[23].OneofWrappers = []interface{}{
		(*TimelineAction_Lifecycle)(nil),
		(*TimelineAction_ApplyFault)(nil),
		(*TimelineAction_RevertFault)(nil),
		(*TimelineAction_Exec)(nil),
		(*TimelineAction_WaitExec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_labcontainers_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_labcontainers_proto_goTypes,
		DependencyIndexes: file_api_v1_labcontainers_proto_depIdxs,
		EnumInfos:         file_api_v1_labcontainers_proto_enumTypes,
		MessageInfos:      file_api_v1_labcontainers_proto_msgTypes,
	}.Build()
	File_api_v1_labcontainers_proto = out.File
	file_api_v1_labcontainers_proto_rawDesc = nil
	file_api_v1_labcontainers_proto_goTypes = nil
	file_api_v1_labcontainers_proto_depIdxs = nil
}
