// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/v1/labcontainers.proto

package labcontainersv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Labcontainers_CreateSession_FullMethodName  = "/labcontainers.v1.Labcontainers/CreateSession"
	Labcontainers_GetSession_FullMethodName     = "/labcontainers.v1.Labcontainers/GetSession"
	Labcontainers_DestroySession_FullMethodName = "/labcontainers.v1.Labcontainers/DestroySession"
	Labcontainers_KeepSession_FullMethodName    = "/labcontainers.v1.Labcontainers/KeepSession"
	Labcontainers_PlanTopology_FullMethodName   = "/labcontainers.v1.Labcontainers/PlanTopology"
	Labcontainers_ApplyTopology_FullMethodName  = "/labcontainers.v1.Labcontainers/ApplyTopology"
	Labcontainers_Exec_FullMethodName           = "/labcontainers.v1.Labcontainers/Exec"
	Labcontainers_Put_FullMethodName            = "/labcontainers.v1.Labcontainers/Put"
	Labcontainers_Lifecycle_FullMethodName      = "/labcontainers.v1.Labcontainers/Lifecycle"
	Labcontainers_ApplyFault_FullMethodName     = "/labcontainers.v1.Labcontainers/ApplyFault"
	Labcontainers_RevertFault_FullMethodName    = "/labcontainers.v1.Labcontainers/RevertFault"
	Labcontainers_RunTimeline_FullMethodName    = "/labcontainers.v1.Labcontainers/RunTimeline"
)

// LabcontainersClient is the client API for Labcontainers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LabcontainersClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	GetSession(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*Session, error)
	DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*Empty, error)
	KeepSession(ctx context.Context, in *KeepSessionRequest, opts ...grpc.CallOption) (*Session, error)
	PlanTopology(ctx context.Context, in *PlanTopologyRequest, opts ...grpc.CallOption) (*NativeApplyResult, error)
	ApplyTopology(ctx context.Context, in *ApplyTopologyRequest, opts ...grpc.CallOption) (*Session, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*Empty, error)
	Lifecycle(ctx context.Context, in *LifecycleRequest, opts ...grpc.CallOption) (*Node, error)
	ApplyFault(ctx context.Context, in *ApplyFaultRequest, opts ...grpc.CallOption) (*Fault, error)
	RevertFault(ctx context.Context, in *FaultRef, opts ...grpc.CallOption) (*Empty, error)
	RunTimeline(ctx context.Context, in *RunTimelineRequest, opts ...grpc.CallOption) (*TimelineResult, error)
}

type labcontainersClient struct {
	cc grpc.ClientConnInterface
}

func NewLabcontainersClient(cc grpc.ClientConnInterface) LabcontainersClient {
	return &labcontainersClient{cc}
}

func (c *labcontainersClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Labcontainers_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labcontainersClient) GetSession(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Labcontainers_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labcontainersClient) DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Labcontainers_DestroySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labcontainersClient) KeepSession(ctx context.Context, in *KeepSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Labcontainers_KeepSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labcontainersClient) PlanTopology(ctx context.Context, in *PlanTopologyRequest, opts ...grpc.CallOption) (*NativeApplyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NativeApplyResult)
	err := c.cc.Invoke(ctx, Labcontainers_PlanTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labcontainersClient) ApplyTopology(ctx context.Context, in *ApplyTopologyRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Labcontainers_ApplyTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labcontainersClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, Labcontainers_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labcontainersClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Labcontainers_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labcontainersClient) Lifecycle(ctx context.Context, in *LifecycleRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, Labcontainers_Lifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labcontainersClient) ApplyFault(ctx context.Context, in *ApplyFaultRequest, opts ...grpc.CallOption) (*Fault, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fault)
	err := c.cc.Invoke(ctx, Labcontainers_ApplyFault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labcontainersClient) RevertFault(ctx context.Context, in *FaultRef, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Labcontainers_RevertFault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labcontainersClient) RunTimeline(ctx context.Context, in *RunTimelineRequest, opts ...grpc.CallOption) (*TimelineResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimelineResult)
	err := c.cc.Invoke(ctx, Labcontainers_RunTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LabcontainersServer is the server API for Labcontainers service.
// All implementations must embed UnimplementedLabcontainersServer
// for forward compatibility.
type LabcontainersServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	GetSession(context.Context, *SessionRef) (*Session, error)
	DestroySession(context.Context, *DestroySessionRequest) (*Empty, error)
	KeepSession(context.Context, *KeepSessionRequest) (*Session, error)
	PlanTopology(context.Context, *PlanTopologyRequest) (*NativeApplyResult, error)
	ApplyTopology(context.Context, *ApplyTopologyRequest) (*Session, error)
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	Put(context.Context, *PutRequest) (*Empty, error)
	Lifecycle(context.Context, *LifecycleRequest) (*Node, error)
	ApplyFault(context.Context, *ApplyFaultRequest) (*Fault, error)
	RevertFault(context.Context, *FaultRef) (*Empty, error)
	RunTimeline(context.Context, *RunTimelineRequest) (*TimelineResult, error)
	mustEmbedUnimplementedLabcontainersServer()
}

// UnimplementedLabcontainersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLabcontainersServer struct{}

func (UnimplementedLabcontainersServer) CreateSession(context.Context, *CreateSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedLabcontainersServer) GetSession(context.Context, *SessionRef) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedLabcontainersServer) DestroySession(context.Context, *DestroySessionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroySession not implemented")
}
func (UnimplementedLabcontainersServer) KeepSession(context.Context, *KeepSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeepSession not implemented")
}
func (UnimplementedLabcontainersServer) PlanTopology(context.Context, *PlanTopologyRequest) (*NativeApplyResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlanTopology not implemented")
}
func (UnimplementedLabcontainersServer) ApplyTopology(context.Context, *ApplyTopologyRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyTopology not implemented")
}
func (UnimplementedLabcontainersServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedLabcontainersServer) Put(context.Context, *PutRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedLabcontainersServer) Lifecycle(context.Context, *LifecycleRequest) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lifecycle not implemented")
}
func (UnimplementedLabcontainersServer) ApplyFault(context.Context, *ApplyFaultRequest) (*Fault, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyFault not implemented")
}
func (UnimplementedLabcontainersServer) RevertFault(context.Context, *FaultRef) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevertFault not implemented")
}
func (UnimplementedLabcontainersServer) RunTimeline(context.Context, *RunTimelineRequest) (*TimelineResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunTimeline not implemented")
}
func (UnimplementedLabcontainersServer) mustEmbedUnimplementedLabcontainersServer() {}
func (UnimplementedLabcontainersServer) testEmbeddedByValue()                       {}

// UnsafeLabcontainersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LabcontainersServer will
// result in compilation errors.
type UnsafeLabcontainersServer interface {
	mustEmbedUnimplementedLabcontainersServer()
}

func RegisterLabcontainersServer(s grpc.ServiceRegistrar, srv LabcontainersServer) {
	// If the following call pancis, it indicates UnimplementedLabcontainersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Labcontainers_ServiceDesc, srv)
}

func _Labcontainers_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabcontainersServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labcontainers_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabcontainersServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labcontainers_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabcontainersServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labcontainers_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabcontainersServer).GetSession(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labcontainers_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabcontainersServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labcontainers_DestroySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabcontainersServer).DestroySession(ctx, req.(*DestroySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labcontainers_KeepSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabcontainersServer).KeepSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labcontainers_KeepSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabcontainersServer).KeepSession(ctx, req.(*KeepSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labcontainers_PlanTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabcontainersServer).PlanTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labcontainers_PlanTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabcontainersServer).PlanTopology(ctx, req.(*PlanTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labcontainers_ApplyTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabcontainersServer).ApplyTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labcontainers_ApplyTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabcontainersServer).ApplyTopology(ctx, req.(*ApplyTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labcontainers_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabcontainersServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labcontainers_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabcontainersServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labcontainers_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabcontainersServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labcontainers_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabcontainersServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labcontainers_Lifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabcontainersServer).Lifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labcontainers_Lifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabcontainersServer).Lifecycle(ctx, req.(*LifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labcontainers_ApplyFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyFaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabcontainersServer).ApplyFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labcontainers_ApplyFault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabcontainersServer).ApplyFault(ctx, req.(*ApplyFaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labcontainers_RevertFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FaultRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabcontainersServer).RevertFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labcontainers_RevertFault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabcontainersServer).RevertFault(ctx, req.(*FaultRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labcontainers_RunTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabcontainersServer).RunTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labcontainers_RunTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabcontainersServer).RunTimeline(ctx, req.(*RunTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Labcontainers_ServiceDesc is the grpc.ServiceDesc for Labcontainers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Labcontainers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "labcontainers.v1.Labcontainers",
	HandlerType: (*LabcontainersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _Labcontainers_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _Labcontainers_GetSession_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _Labcontainers_DestroySession_Handler,
		},
		{
			MethodName: "KeepSession",
			Handler:    _Labcontainers_KeepSession_Handler,
		},
		{
			MethodName: "PlanTopology",
			Handler:    _Labcontainers_PlanTopology_Handler,
		},
		{
			MethodName: "ApplyTopology",
			Handler:    _Labcontainers_ApplyTopology_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _Labcontainers_Exec_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Labcontainers_Put_Handler,
		},
		{
			MethodName: "Lifecycle",
			Handler:    _Labcontainers_Lifecycle_Handler,
		},
		{
			MethodName: "ApplyFault",
			Handler:    _Labcontainers_ApplyFault_Handler,
		},
		{
			MethodName: "RevertFault",
			Handler:    _Labcontainers_RevertFault_Handler,
		},
		{
			MethodName: "RunTimeline",
			Handler:    _Labcontainers_RunTimeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/labcontainers.proto",
}
