// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package networkconfig

import "encoding/json"
import "fmt"
import "reflect"

// DHCP behaviour overrides. Overrides will only have an effect if the
// corresponding DHCP type is enabled.
type DhcpOverrides struct {
	// Unsupported  for dhcp6-overrides when used with the networkd renderer.
	Hostname *string `json:"hostname,omitempty,omitzero"`

	// Unsupported  for dhcp6-overrides when used with the networkd renderer.
	RouteMetric *int `json:"route-metric,omitempty,omitzero"`

	// Unsupported  for dhcp6-overrides when used with the networkd renderer.
	SendHostname *bool `json:"send-hostname,omitempty,omitzero"`

	// UseDns corresponds to the JSON schema field "use-dns".
	UseDns *bool `json:"use-dns,omitempty,omitzero"`

	// UseDomains corresponds to the JSON schema field "use-domains".
	UseDomains *string `json:"use-domains,omitempty,omitzero"`

	// UseHostname corresponds to the JSON schema field "use-hostname".
	UseHostname *bool `json:"use-hostname,omitempty,omitzero"`

	// Unsupported  for dhcp6-overrides when used with the networkd renderer.
	UseMtu *bool `json:"use-mtu,omitempty,omitzero"`

	// UseNtp corresponds to the JSON schema field "use-ntp".
	UseNtp *bool `json:"use-ntp,omitempty,omitzero"`

	// Unsupported  for dhcp6-overrides when used with the networkd renderer.
	UseRoutes *bool `json:"use-routes,omitempty,omitzero"`
}

// Deprecated, see Netplan#default-routes. Set default gateway for IPv4/6, for
// manual address configuration. This requires setting addresses too. Gateway IPs
// must be in a form recognised by inet_pton(3).
type Gateway string

type Mapping struct {
	// Add static addresses to the interface in addition to the ones received through
	// DHCP or RA. Each sequence entry is in CIDR notation, i.e., of the form
	// addr/prefixlen. addr is an IPv4 or IPv6 address as recognised by inet_pton(3)
	// and prefixlen the number of bits of the subnet.
	Addresses []string `json:"addresses,omitempty,omitzero"`

	// Enable DHCP for IPv4. Off by default.
	Dhcp4 *MappingDhcp4 `json:"dhcp4,omitempty,omitzero"`

	// Dhcp4Overrides corresponds to the JSON schema field "dhcp4-overrides".
	Dhcp4Overrides *DhcpOverrides `json:"dhcp4-overrides,omitempty,omitzero"`

	// Enable DHCP for IPv6. Off by default.
	Dhcp6 *MappingDhcp6 `json:"dhcp6,omitempty,omitzero"`

	// Dhcp6Overrides corresponds to the JSON schema field "dhcp6-overrides".
	Dhcp6Overrides *DhcpOverrides `json:"dhcp6-overrides,omitempty,omitzero"`

	// Gateway4 corresponds to the JSON schema field "gateway4".
	Gateway4 *Gateway `json:"gateway4,omitempty,omitzero"`

	// Gateway6 corresponds to the JSON schema field "gateway6".
	Gateway6 *Gateway `json:"gateway6,omitempty,omitzero"`

	// The MTU key represents a device’s Maximum Transmission Unit, the largest size
	// packet or frame, specified in octets (eight-bit bytes), that can be sent in a
	// packet- or frame-based network. Specifying mtu is optional.
	Mtu *int `json:"mtu,omitempty,omitzero"`

	// Set DNS servers and search domains, for manual address configuration. There are
	// two supported fields: addresses: is a list of IPv4 or IPv6 addresses similar to
	// gateway*, and search: is a list of search domains.
	Nameservers *MappingNameservers `json:"nameservers,omitempty,omitzero"`

	// Not required for online, false by default
	Optional *bool `json:"optional,omitempty,omitzero"`

	// Renderer corresponds to the JSON schema field "renderer".
	Renderer *Renderer `json:"renderer,omitempty,omitzero"`

	// Routes corresponds to the JSON schema field "routes".
	Routes []MappingRoutesElem `json:"routes,omitempty,omitzero"`

	AdditionalProperties interface{} `json:"-" mapstructure:",remain"`
}

type MappingBond struct {
	// Add static addresses to the interface in addition to the ones received through
	// DHCP or RA. Each sequence entry is in CIDR notation, i.e., of the form
	// addr/prefixlen. addr is an IPv4 or IPv6 address as recognised by inet_pton(3)
	// and prefixlen the number of bits of the subnet.
	Addresses []string `json:"addresses,omitempty,omitzero"`

	// Enable DHCP for IPv4. Off by default.
	Dhcp4 *MappingDhcp4 `json:"dhcp4,omitempty,omitzero"`

	// Dhcp4Overrides corresponds to the JSON schema field "dhcp4-overrides".
	Dhcp4Overrides *DhcpOverrides `json:"dhcp4-overrides,omitempty,omitzero"`

	// Enable DHCP for IPv6. Off by default.
	Dhcp6 *MappingDhcp6 `json:"dhcp6,omitempty,omitzero"`

	// Dhcp6Overrides corresponds to the JSON schema field "dhcp6-overrides".
	Dhcp6Overrides *DhcpOverrides `json:"dhcp6-overrides,omitempty,omitzero"`

	// Gateway4 corresponds to the JSON schema field "gateway4".
	Gateway4 *Gateway `json:"gateway4,omitempty,omitzero"`

	// Gateway6 corresponds to the JSON schema field "gateway6".
	Gateway6 *Gateway `json:"gateway6,omitempty,omitzero"`

	// All devices matching this ID list will be added to the bond.
	Interfaces []string `json:"interfaces,omitempty,omitzero"`

	// The MTU key represents a device’s Maximum Transmission Unit, the largest size
	// packet or frame, specified in octets (eight-bit bytes), that can be sent in a
	// packet- or frame-based network. Specifying mtu is optional.
	Mtu *int `json:"mtu,omitempty,omitzero"`

	// Set DNS servers and search domains, for manual address configuration. There are
	// two supported fields: addresses: is a list of IPv4 or IPv6 addresses similar to
	// gateway*, and search: is a list of search domains.
	Nameservers *MappingNameservers `json:"nameservers,omitempty,omitzero"`

	// Not required for online, false by default
	Optional *bool `json:"optional,omitempty,omitzero"`

	// Customisation parameters for special bonding options. Time values are specified
	// in seconds unless otherwise specified.
	Parameters *MappingBondParameters `json:"parameters,omitempty,omitzero"`

	// Renderer corresponds to the JSON schema field "renderer".
	Renderer *Renderer `json:"renderer,omitempty,omitzero"`

	// Routes corresponds to the JSON schema field "routes".
	Routes []MappingRoutesElem `json:"routes,omitempty,omitzero"`

	AdditionalProperties interface{} `json:"-" mapstructure:",remain"`
}

// Customisation parameters for special bonding options. Time values are specified
// in seconds unless otherwise specified.
type MappingBondParameters struct {
	// Set the aggregation selection mode. This option is only used in 802.3ad mode.
	AdSelect *MappingBondParametersAdSelect `json:"ad-select,omitempty,omitzero"`

	// If the bond should drop duplicate frames received on inactive ports, set this
	// option to false. If they should be delivered, set this option to true. The
	// default value is false, and is the desirable behaviour in most situations.
	AllSlavesActive *bool `json:"all-slaves-active,omitempty,omitzero"`

	// Specify whether to use any ARP IP target being up as sufficient for a slave to
	// be considered up; or if all the targets must be up. This is only used for
	// active-backup mode when arp-validate is enabled.
	ArpAllTargets *MappingBondParametersArpAllTargets `json:"arp-all-targets,omitempty,omitzero"`

	// Set the interval value for how frequently ARP link monitoring should happen.
	// The default value is 0, which disables ARP monitoring.
	ArpInterval *int `json:"arp-interval,omitempty,omitzero"`

	// IPs of other hosts on the link which should be sent ARP requests in order to
	// validate that a slave is up. This option is only used when arp-interval is set
	// to a value other than 0. At least one IP address must be given for ARP link
	// monitoring to function. Only IPv4 addresses are supported. You can specify up
	// to 16 IP addresses. The default value is an empty list.
	ArpIpTargets []string `json:"arp-ip-targets,omitempty,omitzero"`

	// Configure how ARP replies are to be validated when using ARP link monitoring.
	ArpValidate *MappingBondParametersArpValidate `json:"arp-validate,omitempty,omitzero"`

	// Specify the delay before enabling a link once the link has been lost. The
	// default value is 0.
	DownDelay *int `json:"down-delay,omitempty,omitzero"`

	// Set whether to set all slaves to the same MAC address when adding them to the
	// bond, or how else the system should handle MAC addresses.
	FailOverMacPolicy *MappingBondParametersFailOverMacPolicy `json:"fail-over-mac-policy,omitempty,omitzero"`

	// Specify how many ARP packets to send after failover. Once a link is up on a new
	// slave, a notification is sent and possibly repeated if this value is set to a
	// number greater than 1. The default value is 1 and valid values are between 1
	// and 255. This only affects active-backup mode.
	GratuitousArp *int `json:"gratuitous-arp,omitempty,omitzero"`

	// Set the rate at which LACPDUs are transmitted. This is only useful in 802.3ad
	// mode. Possible values are slow (30 seconds, default), and fast (every second).
	LacpRate *MappingBondParametersLacpRate `json:"lacp-rate,omitempty,omitzero"`

	// Specify the interval between sending Learning packets to each slave. The value
	// range is between 1 and 0x7fffffff. The default value is 1. This option only
	// affects balance-tlb and balance-alb modes.
	LearnPacketInterval *string `json:"learn-packet-interval,omitempty,omitzero"`

	// Specifies the interval for MII monitoring (verifying if an interface of the
	// bond has carrier). The default is 0; which disables MII monitoring.
	MiiMonitorInterval *string `json:"mii-monitor-interval,omitempty,omitzero"`

	// The minimum number of links up in a bond to consider the bond interface to be
	// up.
	MinLinks *int `json:"min-links,omitempty,omitzero"`

	// Set the bonding mode used for the interfaces. The default is balance-rr (round
	// robin).
	Mode *MappingBondParametersMode `json:"mode,omitempty,omitzero"`

	// In balance-rr mode, specifies the number of packets to transmit on a slave
	// before switching to the next. When this value is set to 0, slaves are chosen at
	// random. Allowable values are between 0 and 65535. The default value is 1. This
	// setting is only used in balance-rr mode.
	PacketsPerSlave *int `json:"packets-per-slave,omitempty,omitzero"`

	// Set the reselection policy for the primary slave. On failure of the active
	// slave, the system will use this policy to decide how the new active slave will
	// be chosen and how recovery will be handled.
	PrimaryReselectPolicy *MappingBondParametersPrimaryReselectPolicy `json:"primary-reselect-policy,omitempty,omitzero"`

	// Specifies the transmit hash policy for the selection of slaves. This is only
	// useful in balance-xor, 802.3ad and balance-tlb modes.
	TransmitHashPolicy *MappingBondParametersTransmitHashPolicy `json:"transmit-hash-policy,omitempty,omitzero"`

	// Specify the delay before enabling a link once the link is physically up. The
	// default value is 0.
	UpDelay *int `json:"up-delay,omitempty,omitzero"`

	AdditionalProperties interface{} `json:"-" mapstructure:",remain"`
}

type MappingBondParametersAdSelect string

const MappingBondParametersAdSelectBandwidth MappingBondParametersAdSelect = "bandwidth"
const MappingBondParametersAdSelectCount MappingBondParametersAdSelect = "count"
const MappingBondParametersAdSelectStable MappingBondParametersAdSelect = "stable"

var enumValues_MappingBondParametersAdSelect = []interface{}{
	"stable",
	"bandwidth",
	"count",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MappingBondParametersAdSelect) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MappingBondParametersAdSelect {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MappingBondParametersAdSelect, v)
	}
	*j = MappingBondParametersAdSelect(v)
	return nil
}

type MappingBondParametersArpAllTargets string

const MappingBondParametersArpAllTargetsAll MappingBondParametersArpAllTargets = "all"
const MappingBondParametersArpAllTargetsAny MappingBondParametersArpAllTargets = "any"

var enumValues_MappingBondParametersArpAllTargets = []interface{}{
	"any",
	"all",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MappingBondParametersArpAllTargets) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MappingBondParametersArpAllTargets {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MappingBondParametersArpAllTargets, v)
	}
	*j = MappingBondParametersArpAllTargets(v)
	return nil
}

type MappingBondParametersArpValidate string

const MappingBondParametersArpValidateActive MappingBondParametersArpValidate = "active"
const MappingBondParametersArpValidateAll MappingBondParametersArpValidate = "all"
const MappingBondParametersArpValidateBackup MappingBondParametersArpValidate = "backup"
const MappingBondParametersArpValidateNone MappingBondParametersArpValidate = "none"

var enumValues_MappingBondParametersArpValidate = []interface{}{
	"none",
	"active",
	"backup",
	"all",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MappingBondParametersArpValidate) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MappingBondParametersArpValidate {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MappingBondParametersArpValidate, v)
	}
	*j = MappingBondParametersArpValidate(v)
	return nil
}

type MappingBondParametersFailOverMacPolicy string

const MappingBondParametersFailOverMacPolicyActive MappingBondParametersFailOverMacPolicy = "active"
const MappingBondParametersFailOverMacPolicyFollow MappingBondParametersFailOverMacPolicy = "follow"
const MappingBondParametersFailOverMacPolicyNone MappingBondParametersFailOverMacPolicy = "none"

var enumValues_MappingBondParametersFailOverMacPolicy = []interface{}{
	"none",
	"active",
	"follow",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MappingBondParametersFailOverMacPolicy) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MappingBondParametersFailOverMacPolicy {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MappingBondParametersFailOverMacPolicy, v)
	}
	*j = MappingBondParametersFailOverMacPolicy(v)
	return nil
}

type MappingBondParametersLacpRate string

const MappingBondParametersLacpRateFast MappingBondParametersLacpRate = "fast"
const MappingBondParametersLacpRateSlow MappingBondParametersLacpRate = "slow"

var enumValues_MappingBondParametersLacpRate = []interface{}{
	"fast",
	"slow",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MappingBondParametersLacpRate) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MappingBondParametersLacpRate {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MappingBondParametersLacpRate, v)
	}
	*j = MappingBondParametersLacpRate(v)
	return nil
}

type MappingBondParametersMode string

const MappingBondParametersModeA8023Ad MappingBondParametersMode = "802.3ad"
const MappingBondParametersModeActiveBackup MappingBondParametersMode = "active-backup"
const MappingBondParametersModeBalanceAlb MappingBondParametersMode = "balance-alb"
const MappingBondParametersModeBalanceRr MappingBondParametersMode = "balance-rr"
const MappingBondParametersModeBalanceTlb MappingBondParametersMode = "balance-tlb"
const MappingBondParametersModeBalanceXor MappingBondParametersMode = "balance-xor"
const MappingBondParametersModeBroadcast MappingBondParametersMode = "broadcast"

var enumValues_MappingBondParametersMode = []interface{}{
	"balance-rr",
	"active-backup",
	"balance-xor",
	"broadcast",
	"802.3ad",
	"balance-tlb",
	"balance-alb",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MappingBondParametersMode) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MappingBondParametersMode {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MappingBondParametersMode, v)
	}
	*j = MappingBondParametersMode(v)
	return nil
}

type MappingBondParametersPrimaryReselectPolicy string

const MappingBondParametersPrimaryReselectPolicyAlways MappingBondParametersPrimaryReselectPolicy = "always"
const MappingBondParametersPrimaryReselectPolicyBetter MappingBondParametersPrimaryReselectPolicy = "better"
const MappingBondParametersPrimaryReselectPolicyFailure MappingBondParametersPrimaryReselectPolicy = "failure"

var enumValues_MappingBondParametersPrimaryReselectPolicy = []interface{}{
	"always",
	"better",
	"failure",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MappingBondParametersPrimaryReselectPolicy) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MappingBondParametersPrimaryReselectPolicy {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MappingBondParametersPrimaryReselectPolicy, v)
	}
	*j = MappingBondParametersPrimaryReselectPolicy(v)
	return nil
}

type MappingBondParametersTransmitHashPolicy string

const MappingBondParametersTransmitHashPolicyEncap23 MappingBondParametersTransmitHashPolicy = "encap2+3"
const MappingBondParametersTransmitHashPolicyEncap34 MappingBondParametersTransmitHashPolicy = "encap3+4"
const MappingBondParametersTransmitHashPolicyLayer2 MappingBondParametersTransmitHashPolicy = "layer2"
const MappingBondParametersTransmitHashPolicyLayer23 MappingBondParametersTransmitHashPolicy = "layer2+3"
const MappingBondParametersTransmitHashPolicyLayer34 MappingBondParametersTransmitHashPolicy = "layer3+4"

var enumValues_MappingBondParametersTransmitHashPolicy = []interface{}{
	"layer2",
	"layer3+4",
	"layer2+3",
	"encap2+3",
	"encap3+4",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MappingBondParametersTransmitHashPolicy) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MappingBondParametersTransmitHashPolicy {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MappingBondParametersTransmitHashPolicy, v)
	}
	*j = MappingBondParametersTransmitHashPolicy(v)
	return nil
}

type MappingBridge struct {
	// Add static addresses to the interface in addition to the ones received through
	// DHCP or RA. Each sequence entry is in CIDR notation, i.e., of the form
	// addr/prefixlen. addr is an IPv4 or IPv6 address as recognised by inet_pton(3)
	// and prefixlen the number of bits of the subnet.
	Addresses []string `json:"addresses,omitempty,omitzero"`

	// Enable DHCP for IPv4. Off by default.
	Dhcp4 *MappingDhcp4 `json:"dhcp4,omitempty,omitzero"`

	// Dhcp4Overrides corresponds to the JSON schema field "dhcp4-overrides".
	Dhcp4Overrides *DhcpOverrides `json:"dhcp4-overrides,omitempty,omitzero"`

	// Enable DHCP for IPv6. Off by default.
	Dhcp6 *MappingDhcp6 `json:"dhcp6,omitempty,omitzero"`

	// Dhcp6Overrides corresponds to the JSON schema field "dhcp6-overrides".
	Dhcp6Overrides *DhcpOverrides `json:"dhcp6-overrides,omitempty,omitzero"`

	// Gateway4 corresponds to the JSON schema field "gateway4".
	Gateway4 *Gateway `json:"gateway4,omitempty,omitzero"`

	// Gateway6 corresponds to the JSON schema field "gateway6".
	Gateway6 *Gateway `json:"gateway6,omitempty,omitzero"`

	// All devices matching this ID list will be added to the bridge.
	Interfaces []string `json:"interfaces,omitempty,omitzero"`

	// The MTU key represents a device’s Maximum Transmission Unit, the largest size
	// packet or frame, specified in octets (eight-bit bytes), that can be sent in a
	// packet- or frame-based network. Specifying mtu is optional.
	Mtu *int `json:"mtu,omitempty,omitzero"`

	// Set DNS servers and search domains, for manual address configuration. There are
	// two supported fields: addresses: is a list of IPv4 or IPv6 addresses similar to
	// gateway*, and search: is a list of search domains.
	Nameservers *MappingNameservers `json:"nameservers,omitempty,omitzero"`

	// Not required for online, false by default
	Optional *bool `json:"optional,omitempty,omitzero"`

	// Customisation parameters for special bridging options. Time values are
	// specified in seconds unless otherwise stated.
	Parameters *MappingBridgeParameters `json:"parameters,omitempty,omitzero"`

	// Renderer corresponds to the JSON schema field "renderer".
	Renderer *Renderer `json:"renderer,omitempty,omitzero"`

	// Routes corresponds to the JSON schema field "routes".
	Routes []MappingRoutesElem `json:"routes,omitempty,omitzero"`

	AdditionalProperties interface{} `json:"-" mapstructure:",remain"`
}

// Customisation parameters for special bridging options. Time values are specified
// in seconds unless otherwise stated.
type MappingBridgeParameters struct {
	// Set the period of time to keep a MAC address in the forwarding database after a
	// packet is received.
	AgeingTime *int `json:"ageing-time,omitempty,omitzero"`

	// Specify the period of time the bridge will remain in Listening and Learning
	// states before getting to the Forwarding state. This value should be set in
	// seconds for the systemd backend, and in milliseconds for the NetworkManager
	// backend.
	ForwardDelay *int `json:"forward-delay,omitempty,omitzero"`

	// Specify the interval between two hello packets being sent out from the root and
	// designated bridges. Hello packets communicate information about the network
	// topology.
	HelloTime *int `json:"hello-time,omitempty,omitzero"`

	// Set the maximum age of a hello packet. If the last hello packet is older than
	// that value, the bridge will attempt to become the root bridge.
	MaxAge *int `json:"max-age,omitempty,omitzero"`

	// Set the cost of a path on the bridge. Faster interfaces should have a lower
	// cost. This allows a finer control on the network topology so that the fastest
	// paths are available whenever possible.
	PathCost *int `json:"path-cost,omitempty,omitzero"`

	// Set the priority value for the bridge. This value should be a number between 0
	// and 65535. Lower values mean higher priority. The bridge with the higher
	// priority will be elected as the root bridge.
	Priority *int `json:"priority,omitempty,omitzero"`

	// Define whether the bridge should use Spanning Tree Protocol. The default value
	// is “true”, which means that Spanning Tree should be used.
	Stp *bool `json:"stp,omitempty,omitzero"`

	AdditionalProperties interface{} `json:"-" mapstructure:",remain"`
}

type MappingDhcp4 struct {
	Value interface{}
}

// MarshalJSON implements json.Marshaler.
func (j *MappingDhcp4) MarshalJSON() ([]byte, error) {
	return json.Marshal(j.Value)
}

var enumValues_MappingDhcp4 = []interface{}{
	"yes",
	"no",
	true,
	false,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MappingDhcp4) UnmarshalJSON(value []byte) error {
	var v struct {
		Value interface{}
	}
	if err := json.Unmarshal(value, &v.Value); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MappingDhcp4 {
		if reflect.DeepEqual(v.Value, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MappingDhcp4, v.Value)
	}
	*j = MappingDhcp4(v)
	return nil
}

type MappingDhcp6 struct {
	Value interface{}
}

// MarshalJSON implements json.Marshaler.
func (j *MappingDhcp6) MarshalJSON() ([]byte, error) {
	return json.Marshal(j.Value)
}

var enumValues_MappingDhcp6 = []interface{}{
	"yes",
	"no",
	true,
	false,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MappingDhcp6) UnmarshalJSON(value []byte) error {
	var v struct {
		Value interface{}
	}
	if err := json.Unmarshal(value, &v.Value); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MappingDhcp6 {
		if reflect.DeepEqual(v.Value, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MappingDhcp6, v.Value)
	}
	*j = MappingDhcp6(v)
	return nil
}

// Set DNS servers and search domains, for manual address configuration. There are
// two supported fields: addresses: is a list of IPv4 or IPv6 addresses similar to
// gateway*, and search: is a list of search domains.
type MappingNameservers struct {
	// Addresses corresponds to the JSON schema field "addresses".
	Addresses []string `json:"addresses,omitempty,omitzero"`

	// Search corresponds to the JSON schema field "search".
	Search []string `json:"search,omitempty,omitzero"`
}

type MappingPhysical struct {
	// Add static addresses to the interface in addition to the ones received through
	// DHCP or RA. Each sequence entry is in CIDR notation, i.e., of the form
	// addr/prefixlen. addr is an IPv4 or IPv6 address as recognised by inet_pton(3)
	// and prefixlen the number of bits of the subnet.
	Addresses []string `json:"addresses,omitempty,omitzero"`

	// Enable DHCP for IPv4. Off by default.
	Dhcp4 *MappingDhcp4 `json:"dhcp4,omitempty,omitzero"`

	// Dhcp4Overrides corresponds to the JSON schema field "dhcp4-overrides".
	Dhcp4Overrides *DhcpOverrides `json:"dhcp4-overrides,omitempty,omitzero"`

	// Enable DHCP for IPv6. Off by default.
	Dhcp6 *MappingDhcp6 `json:"dhcp6,omitempty,omitzero"`

	// Dhcp6Overrides corresponds to the JSON schema field "dhcp6-overrides".
	Dhcp6Overrides *DhcpOverrides `json:"dhcp6-overrides,omitempty,omitzero"`

	// Gateway4 corresponds to the JSON schema field "gateway4".
	Gateway4 *Gateway `json:"gateway4,omitempty,omitzero"`

	// Gateway6 corresponds to the JSON schema field "gateway6".
	Gateway6 *Gateway `json:"gateway6,omitempty,omitzero"`

	// This selects a subset of available physical devices by various hardware
	// properties. The following configuration will then apply to all matching
	// devices, as soon as they appear. All specified properties must match.
	Match *MappingPhysicalMatch `json:"match,omitempty,omitzero"`

	// The MTU key represents a device’s Maximum Transmission Unit, the largest size
	// packet or frame, specified in octets (eight-bit bytes), that can be sent in a
	// packet- or frame-based network. Specifying mtu is optional.
	Mtu *int `json:"mtu,omitempty,omitzero"`

	// Set DNS servers and search domains, for manual address configuration. There are
	// two supported fields: addresses: is a list of IPv4 or IPv6 addresses similar to
	// gateway*, and search: is a list of search domains.
	Nameservers *MappingNameservers `json:"nameservers,omitempty,omitzero"`

	// Not required for online, false by default
	Optional *bool `json:"optional,omitempty,omitzero"`

	// Renderer corresponds to the JSON schema field "renderer".
	Renderer *Renderer `json:"renderer,omitempty,omitzero"`

	// Routes corresponds to the JSON schema field "routes".
	Routes []MappingRoutesElem `json:"routes,omitempty,omitzero"`

	// When matching on unique properties such as path or MAC, or with additional
	// assumptions such as ''there will only ever be one wifi device'', match rules
	// can be written so that they only match one device. Then this property can be
	// used to give that device a more specific/desirable/nicer name than the default
	// from udev’s ifnames. Any additional device that satisfies the match rules will
	// then fail to get renamed and keep the original kernel name (and dmesg will show
	// an error).
	SetName *string `json:"set-name,omitempty,omitzero"`

	// Enable wake on LAN. Off by default.
	Wakeonlan *bool `json:"wakeonlan,omitempty,omitzero"`

	AdditionalProperties interface{} `json:"-" mapstructure:",remain"`
}

// This selects a subset of available physical devices by various hardware
// properties. The following configuration will then apply to all matching devices,
// as soon as they appear. All specified properties must match.
type MappingPhysicalMatch struct {
	// Kernel driver name, corresponding to the DRIVER udev property. Globs are
	// supported. Matching on driver is only supported with networkd.
	Driver *string `json:"driver,omitempty,omitzero"`

	// Device’s MAC address in the form xx:xx:xx:xx:xx:xx. Globs are not allowed.
	// Letters must be lowercase.
	Macaddress *string `json:"macaddress,omitempty,omitzero"`

	// Current interface name. Globs are supported, and the primary use case for
	// matching on names, as selecting one fixed name can be more easily achieved with
	// having no match: at all and just using the ID (see above). Note that currently
	// only networkd supports globbing, NetworkManager does not.
	Name *string `json:"name,omitempty,omitzero"`
}

type MappingRoutesElem struct {
	// Metric corresponds to the JSON schema field "metric".
	Metric *int `json:"metric,omitempty,omitzero"`

	// To corresponds to the JSON schema field "to".
	To string `json:"to"`

	// Via corresponds to the JSON schema field "via".
	Via *string `json:"via,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MappingRoutesElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["to"]; raw != nil && !ok {
		return fmt.Errorf("field to in MappingRoutesElem: required")
	}
	type Plain MappingRoutesElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MappingRoutesElem(plain)
	return nil
}

type MappingVlan struct {
	// Add static addresses to the interface in addition to the ones received through
	// DHCP or RA. Each sequence entry is in CIDR notation, i.e., of the form
	// addr/prefixlen. addr is an IPv4 or IPv6 address as recognised by inet_pton(3)
	// and prefixlen the number of bits of the subnet.
	Addresses []string `json:"addresses,omitempty,omitzero"`

	// Enable DHCP for IPv4. Off by default.
	Dhcp4 *MappingDhcp4 `json:"dhcp4,omitempty,omitzero"`

	// Dhcp4Overrides corresponds to the JSON schema field "dhcp4-overrides".
	Dhcp4Overrides *DhcpOverrides `json:"dhcp4-overrides,omitempty,omitzero"`

	// Enable DHCP for IPv6. Off by default.
	Dhcp6 *MappingDhcp6 `json:"dhcp6,omitempty,omitzero"`

	// Dhcp6Overrides corresponds to the JSON schema field "dhcp6-overrides".
	Dhcp6Overrides *DhcpOverrides `json:"dhcp6-overrides,omitempty,omitzero"`

	// Gateway4 corresponds to the JSON schema field "gateway4".
	Gateway4 *Gateway `json:"gateway4,omitempty,omitzero"`

	// Gateway6 corresponds to the JSON schema field "gateway6".
	Gateway6 *Gateway `json:"gateway6,omitempty,omitzero"`

	// VLAN ID, a number between 0 and 4094.
	Id *int `json:"id,omitempty,omitzero"`

	// ID of the underlying device definition on which this VLAN gets created.
	Link *string `json:"link,omitempty,omitzero"`

	// The MTU key represents a device’s Maximum Transmission Unit, the largest size
	// packet or frame, specified in octets (eight-bit bytes), that can be sent in a
	// packet- or frame-based network. Specifying mtu is optional.
	Mtu *int `json:"mtu,omitempty,omitzero"`

	// Set DNS servers and search domains, for manual address configuration. There are
	// two supported fields: addresses: is a list of IPv4 or IPv6 addresses similar to
	// gateway*, and search: is a list of search domains.
	Nameservers *MappingNameservers `json:"nameservers,omitempty,omitzero"`

	// Not required for online, false by default
	Optional *bool `json:"optional,omitempty,omitzero"`

	// Renderer corresponds to the JSON schema field "renderer".
	Renderer *Renderer `json:"renderer,omitempty,omitzero"`

	// Routes corresponds to the JSON schema field "routes".
	Routes []MappingRoutesElem `json:"routes,omitempty,omitzero"`

	AdditionalProperties interface{} `json:"-" mapstructure:",remain"`
}

type NetworkConfigVersion2 struct {
	// Bonds corresponds to the JSON schema field "bonds".
	Bonds NetworkConfigVersion2Bonds `json:"bonds,omitempty,omitzero"`

	// Bridges corresponds to the JSON schema field "bridges".
	Bridges NetworkConfigVersion2Bridges `json:"bridges,omitempty,omitzero"`

	// Ethernets corresponds to the JSON schema field "ethernets".
	Ethernets NetworkConfigVersion2Ethernets `json:"ethernets,omitempty,omitzero"`

	// Renderer corresponds to the JSON schema field "renderer".
	Renderer *Renderer `json:"renderer,omitempty,omitzero"`

	// Version corresponds to the JSON schema field "version".
	Version NetworkConfigVersion2Version `json:"version"`

	// Vlans corresponds to the JSON schema field "vlans".
	Vlans NetworkConfigVersion2Vlans `json:"vlans,omitempty,omitzero"`
}

type NetworkConfigVersion2Bonds map[string]MappingBond

type NetworkConfigVersion2Bridges map[string]MappingBridge

type NetworkConfigVersion2Ethernets map[string]MappingPhysical

type NetworkConfigVersion2Version int

var enumValues_NetworkConfigVersion2Version = []interface{}{
	2,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NetworkConfigVersion2Version) UnmarshalJSON(value []byte) error {
	var v int
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NetworkConfigVersion2Version {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NetworkConfigVersion2Version, v)
	}
	*j = NetworkConfigVersion2Version(v)
	return nil
}

type NetworkConfigVersion2Vlans map[string]MappingVlan

// UnmarshalJSON implements json.Unmarshaler.
func (j *NetworkConfigVersion2) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in NetworkConfigVersion2: required")
	}
	type Plain NetworkConfigVersion2
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NetworkConfigVersion2(plain)
	return nil
}

type Renderer string

const RendererNetworkManager Renderer = "NetworkManager"
const RendererNetworkd Renderer = "networkd"

var enumValues_Renderer = []interface{}{
	"networkd",
	"NetworkManager",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Renderer) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Renderer {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Renderer, v)
	}
	*j = Renderer(v)
	return nil
}
