// Code generated by scripts/cloudinit-open-fields.py; DO NOT EDIT.

package networkconfig

func (value Mapping) MarshalJSON() ([]byte, error) {
	type native Mapping
	return marshalOpenObject(native(value), value.AdditionalProperties)
}

func (value *Mapping) UnmarshalJSON(data []byte) error {
	type native Mapping
	var decoded native
	extra, err := unmarshalOpenObject(data, &decoded)
	if err != nil {
		return err
	}
	decoded.AdditionalProperties = extra
	*value = Mapping(decoded)
	return nil
}

func (value MappingBond) MarshalJSON() ([]byte, error) {
	type native MappingBond
	return marshalOpenObject(native(value), value.AdditionalProperties)
}

func (value *MappingBond) UnmarshalJSON(data []byte) error {
	type native MappingBond
	var decoded native
	extra, err := unmarshalOpenObject(data, &decoded)
	if err != nil {
		return err
	}
	decoded.AdditionalProperties = extra
	*value = MappingBond(decoded)
	return nil
}

func (value MappingBondParameters) MarshalJSON() ([]byte, error) {
	type native MappingBondParameters
	return marshalOpenObject(native(value), value.AdditionalProperties)
}

func (value *MappingBondParameters) UnmarshalJSON(data []byte) error {
	type native MappingBondParameters
	var decoded native
	extra, err := unmarshalOpenObject(data, &decoded)
	if err != nil {
		return err
	}
	decoded.AdditionalProperties = extra
	*value = MappingBondParameters(decoded)
	return nil
}

func (value MappingBridge) MarshalJSON() ([]byte, error) {
	type native MappingBridge
	return marshalOpenObject(native(value), value.AdditionalProperties)
}

func (value *MappingBridge) UnmarshalJSON(data []byte) error {
	type native MappingBridge
	var decoded native
	extra, err := unmarshalOpenObject(data, &decoded)
	if err != nil {
		return err
	}
	decoded.AdditionalProperties = extra
	*value = MappingBridge(decoded)
	return nil
}

func (value MappingBridgeParameters) MarshalJSON() ([]byte, error) {
	type native MappingBridgeParameters
	return marshalOpenObject(native(value), value.AdditionalProperties)
}

func (value *MappingBridgeParameters) UnmarshalJSON(data []byte) error {
	type native MappingBridgeParameters
	var decoded native
	extra, err := unmarshalOpenObject(data, &decoded)
	if err != nil {
		return err
	}
	decoded.AdditionalProperties = extra
	*value = MappingBridgeParameters(decoded)
	return nil
}

func (value MappingPhysical) MarshalJSON() ([]byte, error) {
	type native MappingPhysical
	return marshalOpenObject(native(value), value.AdditionalProperties)
}

func (value *MappingPhysical) UnmarshalJSON(data []byte) error {
	type native MappingPhysical
	var decoded native
	extra, err := unmarshalOpenObject(data, &decoded)
	if err != nil {
		return err
	}
	decoded.AdditionalProperties = extra
	*value = MappingPhysical(decoded)
	return nil
}

func (value MappingVlan) MarshalJSON() ([]byte, error) {
	type native MappingVlan
	return marshalOpenObject(native(value), value.AdditionalProperties)
}

func (value *MappingVlan) UnmarshalJSON(data []byte) error {
	type native MappingVlan
	var decoded native
	extra, err := unmarshalOpenObject(data, &decoded)
	if err != nil {
		return err
	}
	decoded.AdditionalProperties = extra
	*value = MappingVlan(decoded)
	return nil
}
