"""Correct go-jsonschema's open-object JSON codec, not its generated models.

v0.24.1 emits additionalProperties fields but does not consistently preserve
them in JSON codecs. Generate flattening methods for exactly the
structs for which that generator emitted its capture field. No schema-specific
field/type list is maintained here.
"""

from pathlib import Path
import re

target = Path("pkg/cloudinit/networkconfig/zz_generated.go")
source = target.read_text()
types = [
    name for name, fields in re.findall(r"type (\w+) struct \{\n(.*?)\n\}", source, re.S)
    if 'AdditionalProperties interface{} `mapstructure:",remain"`' in fields
]
if not types:
    raise SystemExit("expected upstream open-object capture fields; requalify generator")
source = source.replace(
    'AdditionalProperties interface{} `mapstructure:",remain"`',
    'AdditionalProperties interface{} `json:"-" mapstructure:",remain"`',
)
target.write_text(source)
out = "// Code generated by scripts/cloudinit-open-fields.py; DO NOT EDIT.\n\npackage networkconfig\n"
for name in types:
    if f'func (j *{name}) UnmarshalJSON(' in source:
        raise SystemExit(f"upstream now generates {name} decoding; requalify codec correction")
    out += f'''
func (value {name}) MarshalJSON() ([]byte, error) {{
    type native {name}
    return marshalOpenObject(native(value), value.AdditionalProperties)
}}

func (value *{name}) UnmarshalJSON(data []byte) error {{
    type native {name}
    var decoded native
    extra, err := unmarshalOpenObject(data, &decoded)
    if err != nil {{ return err }}
    decoded.AdditionalProperties = extra
    *value = {name}(decoded)
    return nil
}}
'''
Path("pkg/cloudinit/networkconfig/zz_open_generated.go").write_text(out)
